/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-19 09:34:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/component/navbar.jsp", Long.valueOf(1707991438000L));
    _jspx_dependants.put("/component/design.jsp", Long.valueOf(1707800890000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("	padding: 0%;\r\n");
      out.write("	margin: 0%;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contain {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	display: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-left {\r\n");
      out.write("	width: 65%;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-left .first {\r\n");
      out.write("	width: 45%;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-left .first .left {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	min-height: 100px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-shadow: 7px 7px 10px rgb(133, 134, 129);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-left .first .right {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	min-height: 100px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-shadow: 7px 7px 10px rgb(133, 134, 129);\r\n");
      out.write("	border: 0.px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-left .second {\r\n");
      out.write("	width: 45%;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-left .second .left {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	min-height: 100px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-shadow: 7px 7px 10px rgb(133, 134, 129);\r\n");
      out.write("	border: 0.px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-left .second .right {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	min-height: 100px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-shadow: 7px 7px 10px rgb(133, 134, 129);\r\n");
      out.write("	border: 0.px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-right {\r\n");
      out.write("	width: 30%;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-right .imgdiv {\r\n");
      out.write("	height: auto;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 7px 7px 10px rgb(133, 134, 129);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-success\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("	<div style=\"margin:10px\"><svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24\" width=\"27\"\r\n");
      out.write("			viewBox=\"0 0 576 512\">\r\n");
      out.write("			<!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->\r\n");
      out.write("			<path fill=\"#ffffff\"\r\n");
      out.write("				d=\"M543.8 287.6c17 0 32-14 32-32.1c1-9-3-17-11-24L309.5 7c-6-5-14-7-21-7s-15 1-22 8L10 231.5c-7 7-10 15-10 24c0 18 14 32.1 32 32.1h32V448c0 35.3 28.7 64 64 64H448.5c35.5 0 64.2-28.8 64-64.3l-.7-160.2h32zM256 208c0-8.8 7.2-16 16-16h32c8.8 0 16 7.2 16 16v48h48c8.8 0 16 7.2 16 16v32c0 8.8-7.2 16-16 16H320v48c0 8.8-7.2 16-16 16H272c-8.8 0-16-7.2-16-16V320H208c-8.8 0-16-7.2-16-16V272c0-8.8 7.2-16 16-16h48V208z \" /></svg>\r\n");
      out.write("		</div >\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"#\">Health Is Wealth</a>\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("			<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("					aria-current=\"page\" href=\"Admin_Login.jsp\">\r\n");
      out.write("					<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24\" width=\"24\" viewBox=\"0 0 512 512\"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill=\"#f5f5f5\" d=\"M217.9 105.9L340.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L217.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1L32 320c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM352 416l64 0c17.7 0 32-14.3 32-32l0-256c0-17.7-14.3-32-32-32l-64 0c-17.7 0-32-14.3-32-32s14.3-32 32-32l64 0c53 0 96 43 96 96l0 256c0 53-43 96-96 96l-64 0c-17.7 0-32-14.3-32-32s14.3-32 32-32z\"/></svg>\r\n");
      out.write("					Admin</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("					aria-current=\"page\" href=\"Docture_Login.jsp\">Doctor</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("					aria-current=\"page\" href=\"#\">Appoinment</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("					aria-current=\"page\" href=\"User_Login.jsp\">User</a></li>\r\n");
      out.write("\r\n");
      out.write("				<!--   <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>-->\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("	<div id=\"carouselExampleFade\" class=\"carousel slide carousel-fade\"\r\n");
      out.write("		data-bs-ride=\"carousel\">\r\n");
      out.write("		<div class=\"carousel-inner\">\r\n");
      out.write("			<div class=\"carousel-item active\">\r\n");
      out.write("				<img src=\"image/doc.jpg\" class=\"d-block w-100\" alt=\"...\"\r\n");
      out.write("					height=\"600\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<img src=\"image/doc3.jpg\" class=\"d-block w-100\" alt=\"...\"\r\n");
      out.write("					height=\"600\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<img src=\"image/hos.jpg\" class=\"d-block w-100\" alt=\"...\"\r\n");
      out.write("					height=\"600\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("			data-bs-target=\"#carouselExampleFade\" data-bs-slide=\"prev\">\r\n");
      out.write("			<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("				class=\"visually-hidden\">Previous</span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("			data-bs-target=\"#carouselExampleFade\" data-bs-slide=\"next\">\r\n");
      out.write("			<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("				class=\"visually-hidden\">Next</span>\r\n");
      out.write("		</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"contain\">\r\n");
      out.write("		<h3>KEY FEATURE OF HOSPITAL</h3>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"card-left\">\r\n");
      out.write("				<div class=\"first\">\r\n");
      out.write("					<div class=\"left\">\r\n");
      out.write("						<h>100% SAFE</h>\r\n");
      out.write("						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.\r\n");
      out.write("							Libero reiciendis quos placeat maiores mollitia illum expli</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"right\">\r\n");
      out.write("						<h>100% SAFE</h>\r\n");
      out.write("						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.\r\n");
      out.write("							Libero reiciendis quos placeat maiores mollitia illum expli</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"second\">\r\n");
      out.write("					<div class=\"left\">\r\n");
      out.write("						<h>100% SAFE</h>\r\n");
      out.write("						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.\r\n");
      out.write("							Libero reiciendis quos placeat maiores mollitia illum expli</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"right\">\r\n");
      out.write("						<h>100% SAFE</h>\r\n");
      out.write("						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.\r\n");
      out.write("							Libero reiciendis quos placeat maiores mollitia illum expli</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"card-right\">\r\n");
      out.write("				<img class=\"imgdiv\" src=\"image/doc.jpg\" alt=\"img\" />\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
